WIP: Feature/add authentication to check images on registries
raynigon/lennybot pull request #42
Opened 2023-08-16 07:37 UTC by dbalucas

2023-08-16 08:50 UTC, raynigon requested changes
Please split the encoding into a seperate PR and request review again

2023-08-16 08:50 UTC, raynigon commented on .github/scripts/increment_version.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on setup.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on src/lennybot/__init__.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on src/lennybot/actions/download_resources.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on src/lennybot/actions/update_dockerfile.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on src/lennybot/actions/update_image_tag.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on src/lennybot/actions/update_yaml.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on src/lennybot/config/config.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on src/lennybot/model/state.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on src/lennybot/service/plan.py
Out of scope of this PR.
For the next time please split this to a seperate PR.

2023-08-16 08:50 UTC, raynigon commented on version.txt
This should not be changed by a PR

2023-08-16 09:10 UTC, raynigon requested changes
Please add test case and correct the logic for registries without credentials

2023-08-16 09:10 UTC, raynigon commented on src/lennybot/check/docker_image_available.py
> +            url = f"{realm}?scope={scope}&grant_type=password&service={service}&username={registry_data.username}&password={registry_data.password}&client_id=lennybot&access_type=offline"
```suggestion
            params = {"scope": scope, "grant_type": "password", "service": service, "username": registry_data.username, "password": registry_data.password, "client_id": "lennybot", "access_type": "offline"}
            url = f"{realm}?{url_encode_params(params)}"
```

2023-08-16 09:10 UTC, raynigon commented on src/lennybot/check/docker_image_available.py
> +            url = f"{realm}?scope={scope}&grant_type=password&service={service}&client_id=lennybot&access_type=offline"
```suggestion
            params = {"scope": scope, "grant_type": "password", "service": service, "client_id": "lennybot", "access_type": "offline"}
            url = f"{realm}?{url_encode_params(params)}"
```

2023-08-16 09:10 UTC, raynigon commented on src/lennybot/check/docker_image_available.py
> +        ## TODO: test for unauthenticated
Test Case is missing

2023-08-16 09:10 UTC, raynigon commented on src/lennybot/check/docker_image_available.py
> +        if registry_data.password is None or "":
The handling of registries without credentials should not require a registry defined in the configuration file.

2023-08-16 09:11 UTC, raynigon commented on src/lennybot/check/docker_image_available.py
> +BLOCKED_REGISTRIES = []  # "docker.elastic.co"]  # Requires authentication, but is a public registry
Still needed?

2023-08-16 09:12 UTC, raynigon commented on src/lennybot/check/docker_image_available.py
Create the `url_encode_params` function which takes a dictonary and returns an url encoded string of the parameters.

2023-08-16 09:13 UTC, raynigon commented on src/lennybot/check/docker_image_available.py
> +            scope = authenticate.split('scope="')[1].split('"')[0]
Create Authentication Class and parsing function which returns an object of this class

2023-08-17 14:36 UTC, dbalucas reviewed
remove from config

2023-08-17 14:36 UTC, dbalucas commented on test/lennybot.yaml
> +    bracrebike.arc.io:
```suggestion

```

2023-08-17 14:36 UTC, dbalucas commented on test/lennybot.yaml
>        username: "<REDACTED>"
```suggestion
      username: "USERNAME"
```

2023-08-18 07:09 UTC, raynigon commented on src/lennybot/check/docker_image_available.py
> +        ## TODO: test for unauthenticated
@dbalucas please remove comment from here

2023-08-18 07:09 UTC, raynigon commented on test/config/test_config.py
> +    # pass
@dbalucas please remove comment

2023-08-18 07:09 UTC, raynigon commented on version.txt
Please remove this file from the PR

2023-08-18 07:09 UTC, raynigon commented on versions.state.yaml
Please remove this file from the PR

2023-08-23 13:07 UTC, raynigon approved these changes
LGTM

2023-08-23 13:07 UTC, raynigon commented on src/lennybot/check/docker_image_available.py
> +        response = requests.get(url)
```suggestion
        url = f"{authentication_header.realm}?{urlencode(params)}"
        response = requests.get(url)
```

2023-08-23 13:08 UTC, merged